version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: app-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BOOK_APP_API_BASE_URL: http://localhost:8800
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app-backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db         # Use the service name "db"
      DATABASE_USER: devops
      DATABASE_PASSWORD: test1234
      DATABASE_NAME: test
      DATABASE_PORT: 3306       # Internal port for MySQL

  db:
    image: mysql:8.0
    container_name: mysql-1
    ports:
      - "3307:3306"    # Host port 3307, internal port 3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: devops
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: root1234
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 30s
      retries: 6

volumes:
  my-db:
